modules_dir = "artifacts/"

[[module]]
    name = "curl_adapter"
    # logger_enabled = false

    [module.mounted_binaries]
    curl = "/usr/bin/curl"


[[module]]
    name = "elasticsearch_adapter"
    # logger_enabled = false

    [module.mounted_binaries]
    curl = "/usr/bin/curl"

[[module]]
    name = "subscription_facade"
    # logger_enabled = true
