modules_dir = "artifacts/"

[[module]]
    name = "curl_adapter"
    # logger_enabled = false

    [module.mounted_binaries]
    curl = "/usr/bin/curl"

[[module]]
    name = "elasticsearch_adapter"
    # logger_enabled = false

    [module.mounted_binaries]
    curl = "/usr/bin/curl"

[[module]]
    name = "graph_facade"
    # logger_enabled = true

    [module.wasi]
    preopened_files = ["./tmp-html"]
    # this is where files will be stored
    mapped_dirs = { "tmp-html" = "./tmp-html" }